name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test -v ./...

  deploy:
    name: Deploy to Coolify
    runs-on: ubuntu-latest
    needs: 
      - build
      - test
    steps:
      - name: Trigger Coolify Deploy
        env:
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: >-
          curl -X GET
          "http://164.92.86.63:8000/api/v1/deploy?uuid=phl6ahendh61x4lwg6nh6k24&force=false"
          -H "Authorization: Bearer ${COOLIFY_TOKEN}"
